[package]
name = "init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.72"
gt = { path = "../gt" }
tokio = { version = "1.31.0", features = ["macros", "rt", "rt-multi-thread"] }
