[workspace]
members = ["rsrv", "client", "x0", "xxai", "gid", "xkv", "awp"]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
incremental = true
codegen-units = 1
overflow-checks = false
panic = 'abort'
debug-assertions = false
strip = true
