[package]
name = "gt"
version = "0.0.1"
edition = "2021"
license = "BSL-1.0"
homepage = "https://github.com/xxai-art/rsrv"
repository = "https://github.com/xxai-art/rsrv"
description = "connect helper for greptimedb"

[dependencies]
pgm = { version = "0.0.5" }
