[package]
name = "gid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.72"
coarsetime = "0.1.23"
dashmap = "5.5.0"
x0 = { path = "../x0" }

[dev-dependencies]
tokio-test = "0.4.2"
