[package]
name = "xws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["ws", "headers"] }
headers = "0.3.9"
loginit = "0.1.3"
tracing = "0.1.37"
