[package]
name = "rsrv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
awp = "0.1.2"
tracing = "0.1.37"
axum = "0.6.18"
tower = { version = "0.4.13", features = ["timeout"] }
const-str = "0.5.5"
futures-util = "0.3.28"
tower-http = { version = "0.4.0", features = ["cors", "tokio"] }
ctor = "0.2.2"
anypack = { version = "0.1.10" }
trt = "0.1.1"
xxpg = { version = "0.1.11" }
async-lazy = { version = "0.1.0", features = ["parking_lot", "nightly"] }
tower-cookies = "0.9.0"
xxai = { path = "/Users/z/wac.tax/rust/xxai" }
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
client_id = { path = "../client_id" }
x0 = { path = "../x0" }
fred = { version = "6.3.0", features = ["replicas", "rustls"] }
xxai = { path = "../xxai" }

[dependencies.tokio]
version = "1.28.2"
features = ["macros", "rt-multi-thread"]
