[package]
name = "rsrv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
tracing = "0.1.37"
axum = "0.6.18"
tower = { version = "0.4.13", features = ["timeout"] }
const-str = "0.5.5"
futures-util = "0.3.28"
tower-http = { version = "0.4.1", features = ["cors", "tokio"] }
ctor = "0.2.2"
trt = "0.1.4"
async-lazy = { version = "0.1.0", features = ["parking_lot", "nightly"] }
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
client = { path = "../client" }
x0 = { path = "../x0" }
xxai = { path = "../xxai" }
awp = { path = "../awp" }
xxpg = { path = "../xxpg" }
lazy_static = "1.4.0"
coarsetime = "0.1.23"
serde_json = "1.0.99"
serde = { version = "1.0.164", features = ["derive"] }
vbyte = "0.1.0"

[dependencies.tokio]
version = "1.28.2"
features = ["macros", "rt-multi-thread"]

[dependencies.reqwest]
version = "0.11.18"
features = ["tokio-rustls"]
